# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destName', models.CharField(max_length=255)),
                ('destDescription', models.CharField(max_length=255)),
                ('destPlan', models.CharField(max_length=255)),
                ('dateFrom', models.CharField(max_length=255)),
                ('dateUntil', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('userName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cPassword', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='destinations',
            name='joinedBy',
            field=models.ManyToManyField(related_name='joined', to='belt4.User'),
        ),
        migrations.AddField(
            model_name='destinations',
            name='plannedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannedFor', to='belt4.User'),
        ),
    ]
